-- Returns 1
-- SELECT COALESCE(NULL, 1);

-- Returns TRUE
-- SELECT (42)::BOOLEAN

-- Returns NULL
-- SELECT (NULL)::BOOLEAN

-- Return 1
-- SELECT COALESCE((42)::BOOLEAN::INTEGER, 0);

-- Return 0
-- SELECT COALESCE(NULL::BOOLEAN::INTEGER, 0);

-- Return 0
-- SELECT (COALESCE(NULL::BOOLEAN::INTEGER, 0) + COALESCE(NULL::BOOLEAN::INTEGER, 0));

-- Return 2
-- SELECT (COALESCE(42::BOOLEAN::INTEGER, 0) + COALESCE(42::BOOLEAN::INTEGER, 0)); 