SELECT ('1 day'::INTERVAL);

SELECT ('1 d'::INTERVAL);

SELECT ('1 D'::INTERVAL);

SELECT ('1 day 1 hour'::INTERVAL);

SELECT ('1 Y'::INTERVAL);

SELECT ('1 year 3 months'::INTERVAL);

SELECT ('1 day 1 hour'::INTERVAL) - ('1D'::INTERVAL);

SELECT ('26-Nov-23'::DATE) - ('22-NOV-23'::DATE);

SELECT ('26-Nov-23 16:04 CET'::TIMESTAMP WITH TIME ZONE) + ('5d'::INTERVAL);

SELECT ('25-DEC-2023 16:04 CET'::TIMESTAMP wITH TIME ZONE) - 
	('26-Nov-23 16:04 CET'::TIMESTAMP WITH TIME ZONE);