-- This SQL code is generated by https://sql.toad.cz/

CREATE TABLE users (
 id BIGSERIAL,
 username VARCHAR
);


ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE TABLE comments (
 id BIGSERIAL,
 contents VARCHAR,
 user_id INTEGER,
 post_id INTEGER
);


ALTER TABLE comments ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

CREATE TABLE posts (
 id BIGSERIAL,
 title VARCHAR
);


ALTER TABLE posts ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

ALTER TABLE comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE comments ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id);