SELECT COUNT(*) FROM users;

SELECT * FROM users OFFSET 40;

SELECT * FROM users OFFSET 40 LIMIT 5;

SELECT * FROM products ORDER BY price LIMIT 10;

SELECT * FROM products ORDER BY price DESC LIMIT 10;

SELECT * FROM products ORDER BY price DESC LIMIT 10 OFFSET 10;